In [ ]:
import pandas as pd

s = pd.Series([1, 2, 3, 4], name='A')
s

In [ ]:
index = [i for i in range(1, 5)]
s1 = pd.Series(index, index=index, name='A')
s1

In [ ]:
s2 = pd.Series(index)
print(s2)

In [ ]:
result = s2 * 2
result

In [ ]:
filter_result = s2[s2 > 2]
filter_result

In [ ]:
s2 > 2

In [ ]:
print(type(s2>2))

In [ ]:
import numpy as np

r = pd.Series([1, 2, 3, 4])
r

In [ ]:
print(r.sum())
print(r.mean())
print(r.max())
print(r.min())
print(r.std())
print(r.var())

In [ ]:
a = [11, 22, 33]
s = pd.Series(a)
print(s)

In [ ]:
index = s.index
print(index)

In [ ]:
values = s.values
values

In [ ]:
stats = s.describe()
print(type(stats))
stats

In [ ]:
max_index = s.idxmax()
min_index = s.idxmin()
print(type(min_index))
print(min_index)
print(max_index)

In [ ]:
print(s.dtype)
print(s.shape)
print(s.size)
print(s.head())
print(s.tail())

In [43]:
data = [['Alice', 18, 160], ['Max', 22, 175], ['Apple', 16, 180]]
df = pd.DataFrame(data, columns=['Name', 'Age', 'Height'])
# print(df)
# print(df.dtypes)
df

    Name  Age  Height
0  Alice   18     160
1    Max   22     175
2  Apple   16     180

In [45]:
dic = {'Name': ['Alice', 'Max', 'Apple'], 'Age': [18, 22, 16], 'Height': [160, 175, 180]}
df2 = pd.DataFrame(dic)
df2

    Name  Age  Height
0  Alice   18     160
1    Max   22     175
2  Apple   16     180

In [46]:
import numpy as np
nd = np.array(data)
df3 = pd.DataFrame(nd, columns=['Name', 'Age', 'Height'])
df3

    Name Age Height
0  Alice  18    160
1    Max  22    175
2  Apple  16    180

In [47]:
data1 = [['Alice', 18, 160], ['Max', 22, 175], ['Apple', 16]]
df4 = pd.DataFrame(data1, columns=['Name', 'Age', 'Height'])
df4

    Name  Age  Height
0  Alice   18   160.0
1    Max   22   175.0
2  Apple   16     NaN

In [48]:
dic = {
    'calories': [420, 380, 390],
    'duration': [50, 40, 30]
}
df = pd.DataFrame(dic)
df

   calories  duration
0       420        50
1       380        40
2       390        30

In [51]:
print(df.loc[1])
print(type(df.loc[1]))

calories    380
duration     40
Name: 1, dtype: int64
<class 'pandas.Series'>

In [53]:
print(df.loc[[0, 1]])

   calories  duration
0       420        50
1       380        40

In [54]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['NY', 'LA', 'Chicago', 'Houston']
}

df = pd.DataFrame(data)
df

      Name  Age     City
0    Alice   25       NY
1      Bob   30       LA
2  Charlie   35  Chicago
3    David   40  Houston

In [55]:
print(df.head(2))

    Name  Age City
0  Alice   25   NY
1    Bob   30   LA

In [56]:
print(df.tail(2))

      Name  Age     City
2  Charlie   35  Chicago
3    David   40  Houston

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   City    4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [59]:
df.describe()

             Age
count   4.000000
mean   32.500000
std     6.454972
min    25.000000
25%    28.750000
50%    32.500000
75%    36.250000
max    40.000000

In [61]:
df_sorted = df.sort_values(by='Age', ascending=False)
df_sorted

      Name  Age     City
3    David   40  Houston
2  Charlie   35  Chicago
1      Bob   30       LA
0    Alice   25       NY

In [62]:
df[['Name', 'Age']]

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

In [63]:
df.iloc[1:3]

      Name  Age     City
1      Bob   30       LA
2  Charlie   35  Chicago

In [64]:
df.loc[1:3]

      Name  Age     City
1      Bob   30       LA
2  Charlie   35  Chicago
3    David   40  Houston

In [65]:
df.groupby('City')['Age'].mean()

City
Chicago    35.0
Houston    40.0
LA         30.0
NY         25.0
Name: Age, dtype: float64

In [69]:
print(df.groupby('City')['Age'])

<pandas.api.typing.SeriesGroupBy object at 0x10dad9d00>

In [70]:
df['Age'] = df['Age'].fillna(30)

In [71]:
df.to_csv('output.csv')